import { burgerMenu } from "./modules/burgermenu.js";
import { scrollTrigger } from "./modules/scrolltrigger.js";

burgerMenu();
scrollTrigger();

const artCollection = Vue.createApp({
  created() {
    fetch("http://localhost/aic-api/public/artworks")
      .then((res) => {
        if (!res.ok) {
          throw new Error("Network response was not ok");
        }
        return res.json();
      })
      .then((data) => {
        console.log("Artworks data:", data);
        this.artworksData = data;
      })
      .catch((error) => {
        console.error("Error fetching artwork:", error);
        console.log("Catch block reached");
        this.error = "Failed to fetch artwork details from the API";
      });
  },
  data() {
    return {
      artworksData: [],
      artistName: "",
      title: "",
      place: "",
      publishedDate: "",
      medium: "",
      dimensions: "",
      description: "",
      error: "",
    };
  },
  methods: {
    getArtwork(artworkId) {
      const spinner = `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: none; display: block; shape-rendering: auto;" width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
        <circle cx="50" cy="50" r="32" stroke-width="8" stroke="#d5cfb6" stroke-dasharray="50.26548245743669 50.26548245743669" fill="none" stroke-linecap="round">
          <animateTransform attributeName="transform" type="rotate" dur="1s" repeatCount="indefinite" keyTimes="0;1" values="0 50 50;360 50 50"></animateTransform>
        </circle>
        <circle cx="50" cy="50" r="23" stroke-width="8" stroke="#9d9974" stroke-dasharray="36.12831551628262 36.12831551628262" stroke-dashoffset="36.12831551628262" fill="none" stroke-linecap="round">
          <animateTransform attributeName="transform" type="rotate" dur="1s" repeatCount="indefinite" keyTimes="0;1" values="0 50 50;-360 50 50"></animateTransform>
        </circle>
        <!-- [ldio] generated by https://loading.io/ --></svg>`;

      const artworkCon = document.querySelector("#artworkInfoCon");
      artworkCon.innerHTML = spinner;

      fetch(`https://api.artic.edu/api/v1/artworks/${artworkId}`)
        .then((res) => {
          if (!res.ok) {
            throw new Error("Network response was not ok");
          }
          return res.json();
        })
        .then((data) => {
          console.log("Artwork data:", data);
          const artwork = data.data;
          if (artwork) {
            this.error = "";
            this.artistName = artwork.artist_display;
            this.title = artwork.title;
            this.place = artwork.place_of_origin;
            this.publishedDate = artwork.date_display;
            this.dimensions = artwork.dimensions;
            this.medium = artwork.medium_display;
            this.description = artwork.description;

            artworkCon.innerHTML = `
              <div id="artwork">
                <p>Artist: ${this.artistName}</p>
                <p>Title: ${this.title}</p>
                <p>Place of Origin: ${this.place}</p>
                <p>Published Date: ${this.publishedDate}</p>
                <p>Dimensions: ${this.dimensions}</p>
                <p>Medium: ${this.medium}</p>
                <p>Description: ${this.description}</p>
              </div>`;

            // Scroll to the artwork section after fetching the details
            gsap.to(window, {
              duration: 1.2,
              scrollTo: { y: "#artwork", offsetY: 100 },
            });
          } else {
            this.error = "Artwork not found.";
            artworkCon.innerHTML = `
              <div class="error-message">${this.error}</div>`;
          }
        })
        .catch((error) => {
          console.error("Error fetching artwork:", error);
          this.error = "Failed to fetch artwork details from the API";
          artworkCon.innerHTML = `
            <div class="error-message">${this.error}</div>`;
        });
    },
  },
});

artCollection.mount("#app");
